name: PR Media Involvement Request
description: Fill out this form to request PR supoort for an event.
title: "PR Media Involvement for [event name]"
labels: ["Corporate Event", "PR Request", "Events"]

body:
  - type: textarea
    id: event-name
    validations:
      required: true
    attributes:
      label: What is the event?

  - type: textarea
    id: event-epic
    validations:
      required: true
    attributes:
      label: What is the event Epic that this PR request relates to?
      description: |
        Place a link to the issue epic.

  - type: textarea
    id: event-campaign-tag
    validations:
      required: false
    attributes:
      description: Please include the event capaign tag if it is needed
      label: What is the event cammpaign tag?

  - type: textarea
    id: who
    validations:
      required: true
    attributes:
      label: ":girl: Who?"
      value: |
        * Who are we trying to bring to the event?
        * Contact info for guest(s)
        * Who will be the onsite DRI to host this event?

  - type: textarea
    id: Purpose_Reasoning_Goals
    attributes:
      label: ":trophy: Purpose / Reasoning / Goals"
      value: |
        Please add in value this will bring to event/ driing goals.

  - type: textarea
    id: cost_payment
    attributes:
      label: ":moneybag: Cost / Payment"
      value: |
        * What fees are involved? Will we be paying for their travel? Will we need to pay for setup? Power? Internet? AV?
        * Have they been setup in tilapi? DRI will be responsible for setting up billing with vendor and setting budgeting expectations with planning team
        * What team/ project is thing being billed to?

  - type: textarea
    id: onsite_requirements
    attributes:
      label: ":microphone: Onsite Requirements: Space, Time, Special Arrangements."
      value: |
        * Does guest need private space? What other needs or requiremnent must be met for them onsite?

  - type: textarea
    id: shipping
    attributes:
      label: ":package: Shipping"
      value: |
        * Will they be shipping anythigng to the venue?

  - type: textarea
    id: planning
    attributes:
      label: ":paperclip: Anything else planning team needs to know?"

